/**
 * editorStore — lightweight bridge between the active TipTap editor and
 * the Meyvn AI panel.
 *
 * The TipTap editor instance lives inside RichTextEditor and cannot be
 * accessed directly from outside.  This store provides two bridges:
 *
 * 1. Live content (read direction: editor → Meyvn)
 *    NodeEditor publishes plain-text snapshots here (debounced alongside the
 *    normal auto-save) so Meyvn always has an up-to-date view of the scene.
 *
 * 2. Pending suggestion (write direction: Meyvn → editor)
 *    MeyvnPanel sets a pendingSuggestion after the author approves.
 *    RichTextEditor watches it, shows an approval banner, and applies the
 *    prose to the document when the author confirms.
 */

import { create } from 'zustand';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** How Meyvn's suggested prose should be inserted into the document. */
export type SuggestionAction = 'insert_at_cursor' | 'append';

export interface PendingSuggestion {
  /** The raw prose text generated by Meyvn (may contain \n\n paragraph breaks). */
  text: string;
  /** Where to place it in the editor. */
  action: SuggestionAction;
}

interface EditorState {
  // ── Live context (editor → Meyvn) ─────────────────────────────────────────
  /** Plain-text content of the currently open node (debounced ~500 ms). */
  liveContent: string;
  /** Title of the currently open writing node (scene / chapter / note). */
  activeNodeTitle: string;

  /**
   * Called by NodeEditor every time content is saved.
   * @param content    Plain text extracted from TipTap JSON.
   * @param nodeTitle  Title of the node being edited.
   */
  setLiveContext: (content: string, nodeTitle: string) => void;
  /** Called when the user closes or navigates away from all nodes. */
  clearLiveContext: () => void;

  // ── Pending suggestion (Meyvn → editor) ───────────────────────────────────
  /**
   * Prose suggestion staged by MeyvnPanel, waiting for the author to approve.
   * Null when no suggestion is pending.
   */
  pendingSuggestion: PendingSuggestion | null;
  /** Stage a suggestion for the editor to pick up and display in its banner. */
  setPendingSuggestion: (suggestion: PendingSuggestion) => void;
  /** Clear after the author approves or discards the suggestion. */
  clearPendingSuggestion: () => void;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useEditorStore = create<EditorState>((set) => ({
  liveContent: '',
  activeNodeTitle: '',
  pendingSuggestion: null,

  setLiveContext: (content, nodeTitle) =>
    set({ liveContent: content, activeNodeTitle: nodeTitle }),

  clearLiveContext: () =>
    set({ liveContent: '', activeNodeTitle: '' }),

  setPendingSuggestion: (suggestion) =>
    set({ pendingSuggestion: suggestion }),

  clearPendingSuggestion: () =>
    set({ pendingSuggestion: null }),
}));
